### ISSUE TITLE
Move group-id X from vg-request to step vg-request-with-auth

### ISSUE THREAD

**Issue by r10s** [nextleap-project/countermitm#33]
Step 2 of the "Out-of-band verified groups"-protocol reads as follows ...

> in step 2 Bob manually confirms he wants to join the group X.
> before his device sends the ``vg-request-X`` message.

... where the X is a placeholder for the group name and/or id, imu.

During implementation, I found it more useful to move X to step 4b / vg-request-with-auth. Reasons:

- the inviter side gets X when it really needs it in step 6 then - otherwise, the inviter has to track which X is used in which secure join
- X is not needed by the inviter in the response to step 2
- vg-request may not be sent when taking the shortcut in 2a; so we have to add it to 4b anyway
- the group id gets encrypted (in step 2 it would be sent unencrypted)
- finally, elegance: in vg-request-with-auth already the other parameters are send :)

**Comment by azul** [comment]
Okay... we already moved on from this introducing the metadata in the boostrap code.
I checked we still fulfill the desired property that this issue was addressing.
We do not leak the group name publicly:
Verified contact and verified group data on the wires is the same up to step 4 and from there on all messages are encrypted and the keys have been verified.
